version: '3'
services:
  web:
    image: odoo:14.0
    container_name: odoo_produccion
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /srv/odoo/config:/etc/odoo
      - /home/marco/odoo-docker-postgres/addons:/mnt/extra-addons
      
  db:
    image: postgres:11.1
    container_name: odoo_base
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: odoo_pgadmin
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: aulavirtualturismo@gmail.com
       PGADMIN_DEFAULT_PASSWORD: matito
       PGADMIN_LISTEN_PORT: 80
    ports:
       - "8080:80"
    links:
       - "db:pgsql-server"
       
  nginx: 
    image: nginx:latest
    container_name: odoo_nginx
    depends_on:
      - web
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
      
volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-nginx-data:
