version: '3'
services:
  web:
    image: odoo:13.0
    container_name: odoo_produccion
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069/tcp"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /srv/odoo/config:/etc/odoo
      - /srv/odoo/addons:/mnt/extra-addons
      
  db:
    image: postgres:11.1
    container_name: odoo_base
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432/tcp"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data:
